/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: eccbf1c6-aef4-4a21-a046-49998844c8bc

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the function $f(n)$ as the minimal value of $|C| + |B|$ where $B \subset (2n, 4n)$ and $C \subset (n, 2n)$ is sum-free with respect to $B$. We formalize the problem by defining `SumGraph` and `f`. We state the assumption provided by the user as `MainAssumption`, which asserts the existence of a set $B$ with specific properties related to the independence number of the associated sum graph. We then prove `f_bound_complete`, which shows that under `MainAssumption`, $f(n) \le n^{3/5 + \epsilon}$ for any $\epsilon > 0$ and sufficiently large $n$. This confirms the bound $f(n) \le n^{3/5 + o(1)}$.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Checking if Finset.Ioo, SimpleGraph, and Real.rpow are available.
-/
#check Finset.Ioo
#check SimpleGraph
#check Real.rpow

/-
Definitions for the problem. V(n) is the set of integers in (n, 2n). SumGraph(n, B) is the graph on V(n) where x~y if x+y in B. f(n) is the minimum of alpha(G_B) + |B|. Assumption is the given condition.
-/
open SimpleGraph Finset Real Set

def V (n : ℕ) := {x : ℕ // x ∈ Finset.Ioo n (2*n)}

instance (n : ℕ) : Fintype (V n) :=
  Fintype.ofFinset (Finset.Ioo n (2*n)) (fun _ => Iff.rfl)

def SumGraph (n : ℕ) (B : Finset ℕ) : SimpleGraph (V n) :=
  { Adj := fun x y => x ≠ y ∧ x.1 + y.1 ∈ B,
    symm := fun x y ⟨hxy, h⟩ => ⟨hxy.symm, by rwa [add_comm]⟩,
    loopless := fun x ⟨h, _⟩ => h rfl }

noncomputable def f (n : ℕ) : ℕ :=
  sInf ((fun (B : Finset ℕ) => (SumGraph n B).indepNum + B.card) '' { B : Finset ℕ | ∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n) })

def Assumption : Prop :=
  ∀ ε > 0, ∃ N : ℕ, ∀ n ≥ N, ∀ p : ℝ, 0 < p → p ≤ 1/2 →
    ∃ B : Finset ℕ, (∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n)) ∧
    (B.card : ℝ) ≤ 3 * (n : ℝ) * p ∧
    ((SumGraph n B).indepNum : ℝ) ≤ p^(-(1.5 : ℝ)) * (n : ℝ)^ε

/-
For large enough n, p = n^(-2/5) is a valid probability (between 0 and 1/2).
-/
lemma p_valid : ∃ N : ℕ, ∀ n ≥ N, let p := (n : ℝ)^(-(2:ℝ)/5); 0 < p ∧ p ≤ 1/2 := by
  -- We need $n^{2/5} \geq 2$, i.e., $n \geq 2^{5/2}$.
  use 32;
  intro n hn;
  norm_num [ Real.rpow_pos_of_pos, show n > 0 by linarith ];
  rw [ Real.rpow_neg ( by positivity ) ];
  rw [ inv_le_comm₀, Real.le_rpow_iff_log_le ] <;> norm_num;
  · rw [ div_mul_eq_mul_div, le_div_iff₀' ] <;> norm_num;
    rw [ ← Real.log_rpow, ← Real.log_rpow, Real.log_le_log_iff ] <;> norm_cast <;> nlinarith [ Nat.pow_le_pow_left hn 2 ];
  · linarith;
  · positivity

/-
Arithmetic inequality for the final bound. For large n, 3*n^(3/5) + n^(3/5 + ε/2) <= n^(3/5 + ε).
-/
lemma bound_ineq (ε : ℝ) (hε : 0 < ε) : ∃ N : ℕ, ∀ n ≥ N, 3 * (n : ℝ)^(3/5 : ℝ) + (n : ℝ)^(3/5 + ε/2) ≤ (n : ℝ)^(3/5 + ε) := by
  -- We can divide both sides by $n^{3/5}$ to simplify the inequality.
  suffices h_simplified : ∃ N : ℕ, ∀ n ≥ N, 3 + (n : ℝ)^((3 / 5 : ℝ) + (ε / 2) - (3 / 5 : ℝ)) ≤ (n : ℝ)^(ε) by
    obtain ⟨ N, hN ⟩ := h_simplified; use N + 1; intros n hn; convert mul_le_mul_of_nonneg_right ( hN n ( by linarith ) ) ( Real.rpow_nonneg ( Nat.cast_nonneg n ) ( 3 / 5 : ℝ ) ) using 1 <;> ring;
    · rw [ ← Real.rpow_add ( by norm_cast; linarith ) ];
    · rw [ ← Real.rpow_add ( by norm_cast; linarith ), add_comm ];
  -- We can divide both sides by $n^{\epsilon/2}$ to get $3n^{-\epsilon/2} + 1 \leq n^{\epsilon/2}$.
  suffices h_simplified : ∃ N : ℕ, ∀ n ≥ N, 3 * (n : ℝ)^(-ε / 2) + 1 ≤ (n : ℝ)^(ε / 2) by
    obtain ⟨ N, hN ⟩ := h_simplified; use N + 1; intros n hn; convert mul_le_mul_of_nonneg_left ( hN n <| by linarith ) ( Real.rpow_nonneg ( Nat.cast_nonneg n ) ( ε / 2 ) ) using 1 <;> ring;
    · field_simp;
      rw [ mul_add, mul_left_comm, ← Real.rpow_add ( by norm_cast; linarith ) ] ; norm_num ; ring;
    · rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( Nat.cast_nonneg _ ) ] ; ring;
  -- We'll use that $3n^{-\epsilon/2} + 1 \leq n^{\epsilon/2}$ for sufficiently large $n$.
  have h_lim : Filter.Tendsto (fun n : ℕ => (n : ℝ)^(ε / 2) - 3 * (n : ℝ)^(-ε / 2) - 1) Filter.atTop Filter.atTop := by
    field_simp;
    exact Filter.Tendsto.atTop_add ( Filter.Tendsto.atTop_add ( tendsto_rpow_atTop ( by positivity ) |> Filter.Tendsto.comp <| tendsto_natCast_atTop_atTop ) <| Filter.Tendsto.neg <| tendsto_const_nhds.mul <| tendsto_rpow_neg_atTop ( by positivity ) |> Filter.Tendsto.comp <| tendsto_natCast_atTop_atTop ) tendsto_const_nhds;
  exact Filter.eventually_atTop.mp ( h_lim.eventually_ge_atTop 0 ) |> fun ⟨ N, hN ⟩ => ⟨ N, fun n hn => by linarith [ hN n hn ] ⟩

/-
Helper calculation lemma. Verifies the algebraic simplifications for the specific choice of p = n^(-2/5).
-/
lemma calc_val (n : ℕ) (δ : ℝ) (hn : 0 < n) :
  let p := (n : ℝ)^(-(2:ℝ)/5);
  3 * (n : ℝ) * p = 3 * (n : ℝ)^(3/5 : ℝ) ∧
  p^(-(1.5 : ℝ)) * (n : ℝ)^δ = (n : ℝ)^(3/5 + δ) := by
    norm_num [ mul_assoc, ← Real.rpow_add ( Nat.cast_pos.mpr hn ), ← Real.rpow_mul ( Nat.cast_nonneg n ) ];
    rw [ ← Real.rpow_one_add' ] <;> norm_num

/-
Simple arithmetic inequality: 3 n^(3/5) + n^(3/5 + δ/2) <= 3 n^(3/5) + n^(3/5 + δ).
-/
lemma arithmetic_step (n : ℕ) (δ : ℝ) (hn : 1 ≤ n) (hδ : 0 < δ) :
  3 * (n : ℝ)^(3/5 : ℝ) + (n : ℝ)^(3/5 + δ/2) ≤ 3 * (n : ℝ)^(3/5 : ℝ) + (n : ℝ)^(3/5 + δ) := by
    exact add_le_add_left ( Real.rpow_le_rpow_of_exponent_le ( by norm_cast ) ( by linarith ) ) _

/-
Checking the type of Assumption.
-/
#check Assumption

/-
Checking the definition of Assumption to see the type of epsilon.
-/
#print Assumption

/-
Corrected assumption definition and the lemma applying it.
-/
def MainAssumption : Prop :=
  ∀ (ε : ℝ), 0 < ε → ∃ N : ℕ, ∀ n ≥ N, ∀ (p : ℝ), 0 < p → p ≤ 1/2 →
    ∃ B : Finset ℕ, (∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n)) ∧
    (B.card : ℝ) ≤ 3 * (n : ℝ) * p ∧
    ((SumGraph n B).indepNum : ℝ) ≤ p^(-(1.5 : ℝ)) * (n : ℝ)^ε

lemma assumption_applied (δ : ℝ) (hδ : 0 < δ) (h : MainAssumption) :
  ∃ N : ℕ, ∀ n ≥ N, let p := (n : ℝ)^(-(2:ℝ)/5);
  ∃ B : Finset ℕ, (∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n)) ∧
  (B.card : ℝ) ≤ 3 * (n : ℝ) * p ∧
  ((SumGraph n B).indepNum : ℝ) ≤ p^(-(1.5 : ℝ)) * (n : ℝ)^δ := by
  obtain ⟨N1, hN1⟩ := h δ hδ
  obtain ⟨N2, hN2⟩ := p_valid
  use max N1 N2
  intro n hn
  have hn1 : n ≥ N1 := le_trans (le_max_left N1 N2) hn
  have hn2 : n ≥ N2 := le_trans (le_max_right N1 N2) hn
  specialize hN2 n hn2
  specialize hN1 n hn1 ((n : ℝ)^(-(2:ℝ)/5)) hN2.1 hN2.2
  exact hN1

/-
Existence of a good set B for large n.
-/
lemma exists_good_B (δ : ℝ) (hδ : 0 < δ) (h : MainAssumption) :
  ∃ N : ℕ, ∀ n ≥ N, ∃ B : Finset ℕ,
    (∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n)) ∧
    (B.card : ℝ) + (SumGraph n B).indepNum ≤ 3 * (n : ℝ)^(3/5 : ℝ) + (n : ℝ)^(3/5 + δ) := by
      -- Obtain $N$ from `assumption_applied` with $\delta$.
      obtain ⟨N1, hN1⟩ := assumption_applied δ hδ h;
      -- Obtain $N_2$ from `p_valid`.
      obtain ⟨N2, hN2⟩ := p_valid;
      use Max.max N1 N2 + 1;
      intro n hn; obtain ⟨ B, hB₁, hB₂, hB₃ ⟩ := hN1 n ( by linarith [ le_max_left N1 N2 ] ) ; use B; refine' ⟨ hB₁, _ ⟩ ; convert add_le_add hB₂ hB₃ using 1 ; ring;
      rw [ ← Real.rpow_one_add' ] <;> norm_num ; ring;
      rw [ ← Real.rpow_mul ( Nat.cast_nonneg _ ), ← Real.rpow_add' ( Nat.cast_nonneg _ ) ] <;> norm_num;
      linarith

/-
For any delta > 0, for large enough n, there exists a set B such that |B| + alpha(G_B) <= 3 n^(3/5) + n^(3/5 + delta).
-/
lemma exists_good_B_bound (δ : ℝ) (hδ : 0 < δ) (h : MainAssumption) :
  ∃ N : ℕ, ∀ n ≥ N, ∃ B : Finset ℕ,
    (∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n)) ∧
    (B.card : ℝ) + (SumGraph n B).indepNum ≤ 3 * (n : ℝ)^(3/5 : ℝ) + (n : ℝ)^(3/5 + δ) := by
      exact?

/-
Main theorem: f(n) <= n^(3/5 + ε) for large n.
-/
theorem f_bound (h : MainAssumption) : ∀ (ε : ℝ), 0 < ε → ∃ N : ℕ, ∀ n ≥ N, (f n : ℝ) ≤ (n : ℝ)^((3 : ℝ)/5) * (n : ℝ)^ε := by
  intro ε hε
  obtain ⟨N, hN⟩ := exists_good_B_bound (ε / 2) (half_pos hε) h;
  -- By combining the results from `exists_good_B_bound` and `bound_ineq`, we get the desired inequality for `f(n)`.
  obtain ⟨M, hM⟩ := bound_ineq ε hε;
  use max N M + 1;
  intro n hn;
  obtain ⟨B, hB₁, hB₂⟩ := hN n (by
  linarith [ Nat.le_max_left N M, Nat.le_max_right N M ]);
  have hB₃ : (B.card : ℝ) + (SumGraph n B).indepNum ≤ (n : ℝ)^(3/5 + ε) := by
    exact le_trans hB₂ ( hM n ( by linarith [ le_max_right N M ] ) );
  refine' le_trans _ ( hB₃.trans _ );
  · norm_cast;
    refine' Nat.sInf_le _;
    grind;
  · rw [ ← Real.rpow_add ( by norm_cast; linarith [ le_max_left N M, le_max_right N M ] ) ]

/-
Checking the types of the helper lemmas and definitions.
-/
#check exists_good_B
#check bound_ineq
#check p_valid
#check Assumption
#check MainAssumption

/-
Checking existence of declarations.
-/
#check exists_good_B
#check assumption_applied
#check f_bound

/-
Final theorem with complete proof.
-/
theorem f_bound_final (h : MainAssumption) : ∀ (ε : ℝ), 0 < ε → ∃ N : ℕ, ∀ n ≥ N, (f n : ℝ) ≤ (n : ℝ)^((3 : ℝ)/5) * (n : ℝ)^ε := by
  convert f_bound h

/-
Final theorem: f(n) <= n^(3/5 + ε) for large n, with complete proof.
-/
theorem f_bound_complete (h : MainAssumption) : ∀ (ε : ℝ), 0 < ε → ∃ N : ℕ, ∀ n ≥ N, (f n : ℝ) ≤ (n : ℝ)^((3 : ℝ)/5) * (n : ℝ)^ε := by
  intro ε hε
  obtain ⟨N_good, hN_good⟩ := exists_good_B (ε / 2) (half_pos hε) h
  obtain ⟨N_bound, hN_bound⟩ := bound_ineq ε hε
  use max (max N_good N_bound) 1
  intro n hn
  have hn_pos : 0 < n := by
    have : 1 ≤ n := le_trans (le_max_right _ _) hn
    linarith
  have hn_good : n ≥ N_good := le_trans (le_trans (le_max_left N_good N_bound) (le_max_left _ _)) hn
  have hn_bound : n ≥ N_bound := le_trans (le_trans (le_max_right N_good N_bound) (le_max_left _ _)) hn
  
  specialize hN_good n hn_good
  specialize hN_bound n hn_bound
  obtain ⟨B, hB_cond, hB_val⟩ := hN_good
  
  have h_in_set : B ∈ { B : Finset ℕ | ∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n) } := hB_cond
  have h_val_in_image : (SumGraph n B).indepNum + B.card ∈ (fun (B : Finset ℕ) => (SumGraph n B).indepNum + B.card) '' { B : Finset ℕ | ∀ b ∈ B, b ∈ Finset.Ioo (2*n) (4*n) } := ⟨B, h_in_set, rfl⟩
  have h_f_le : f n ≤ (SumGraph n B).indepNum + B.card := csInf_le ⟨0, fun _ _ => Nat.zero_le _⟩ h_val_in_image
  
  rw [← Real.rpow_add (Nat.cast_pos.mpr hn_pos)]
  calc (f n : ℝ) ≤ ((SumGraph n B).indepNum + B.card : ℕ) := Nat.cast_le.mpr h_f_le
      _ = (B.card : ℝ) + (SumGraph n B).indepNum := by push_cast; ring
      _ ≤ 3 * (n : ℝ)^(3/5 : ℝ) + (n : ℝ)^(3/5 + ε/2) := hB_val
      _ ≤ (n : ℝ)^(3/5 + ε) := hN_bound