/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 47d9df7b-56e5-432b-964f-51750376df3a
-/

/-
We formalized the definition of the diagonal Ramsey number $R(k)$ and proved the lower bound $R(k) > (\sqrt{2})^k$ for $k \ge 3$.
The proof uses the probabilistic method: we show that the expected number of monochromatic $k$-cliques in a random graph on $n = \lfloor 2^{k/2} \rfloor$ vertices is less than 1.
This implies the existence of a graph with no monochromatic $k$-cliques, and thus $R(k) > n$.
The main theorem is `diagonalRamsey_gt_sqrt2_pow_k`.
We assumed the finiteness of Ramsey numbers (`∃ M, IsRamsey k M`) as a hypothesis for the main theorem, as proving Ramsey's theorem itself was outside the scope of the lower bound proof.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Let $R(k)$ mean the *diagonal* Ramsey number $R(k,k)$: the smallest $n$ such that **every** red/blue coloring of the edges of (K_n) contains a monochromatic (K_k).
-/
open SimpleGraph

/-- `IsRamsey k n` means that for every graph on `n` vertices,
either the graph has a clique of size `k` or its complement has a clique of size `k`.
This corresponds to every 2-coloring of the edges of K_n having a monochromatic K_k. -/
def IsRamsey (k n : ℕ) : Prop :=
  ∀ (G : SimpleGraph (Fin n)), (∃ (s : Finset (Fin n)), G.IsNClique k s) ∨ (∃ (s : Finset (Fin n)), Gᶜ.IsNClique k s)

/-- The diagonal Ramsey number `R(k)` is the smallest `n` such that `IsRamsey k n`. -/
noncomputable def diagonalRamsey (k : ℕ) : ℕ :=
  sInf { n | IsRamsey k n }

/-
The sum of the number of monochromatic $k$-cliques over all graphs on $n$ vertices is $\binom{n}{k} 2^{\binom{n}{2} - \binom{k}{2} + 1}$.
-/
open SimpleGraph

/-- The number of monochromatic `k`-cliques in a graph `G` on `n` vertices. -/
def count_bad_cliques {n : ℕ} (G : SimpleGraph (Fin n)) (k : ℕ) : ℕ :=
  (Finset.filter (fun s => G.IsNClique k s) (Finset.powersetCard k Finset.univ)).card +
  (Finset.filter (fun s => Gᶜ.IsNClique k s) (Finset.powersetCard k Finset.univ)).card

/-- The sum of `count_bad_cliques` over all graphs on `n` vertices is bounded. -/
lemma sum_count_bad_cliques_eq (n k : ℕ) :
    ∑ G : SimpleGraph (Fin n), (count_bad_cliques G k : ℝ) =
    (Nat.choose n k : ℝ) * 2 * 2 ^ ((Nat.choose n 2) - (Nat.choose k 2)) := by
  -- For a fixed $S$, the number of graphs where $S$ is a clique is $2^{\binom{n}{2} - \binom{k}{2}}$.
  have h_count_cliques (S : Finset (Fin n)) (hS : S.card = k) : (Finset.card (Finset.filter (fun G => G.IsNClique k S) (Finset.univ : Finset (SimpleGraph (Fin n))))) = 2 ^ (Nat.choose n 2 - Nat.choose k 2) := by
    -- The number of graphs where $S$ is a clique is equal to the number of ways to choose the remaining edges, which is $2^{\binom{n}{2} - \binom{k}{2}}$.
    have h_clique_count : Finset.card (Finset.filter (fun G : SimpleGraph (Fin n) => G.IsNClique k S) (Finset.univ : Finset (SimpleGraph (Fin n)))) = Finset.card (Finset.powerset (Finset.filter (fun e => e.1 < e.2 ∧ (e.1 ∉ S ∨ e.2 ∉ S)) (Finset.univ : Finset (Fin n × Fin n)))) := by
      refine' Finset.card_bij _ _ _ _;
      use fun G hG => Finset.filter ( fun e => e.1 < e.2 ∧ G.Adj e.1 e.2 ) ( Finset.univ.filter ( fun e => e.1 < e.2 ∧ ( e.1 ∉ S ∨ e.2 ∉ S ) ) );
      · aesop_cat;
      · intro G₁ hG₁ G₂ hG₂ h_eq; ext v w; by_cases hv : v ∈ S <;> by_cases hw : w ∈ S <;> simp_all +decide [ SimpleGraph.IsNClique ] ;
        · have := hG₁.1 hv hw; have := hG₂.1 hv hw; aesop;
        · by_cases hvw : v < w <;> by_cases hwv : w < v <;> simp_all +decide [ Finset.ext_iff, SimpleGraph.adj_comm ];
          · simpa [ SimpleGraph.adj_comm ] using h_eq w v hwv ( by tauto );
          · simp_all +decide [ le_antisymm hwv hvw ];
        · by_cases hvw : v < w <;> simp_all +decide [ Finset.ext_iff, SimpleGraph.adj_comm ];
          have := h_eq w v; simp_all +decide [ SimpleGraph.adj_comm ] ;
          cases lt_or_eq_of_le hvw <;> aesop;
        · by_cases hvw : v < w <;> by_cases hwv : w < v <;> simp_all +decide [ Finset.ext_iff ];
          · simpa [ SimpleGraph.adj_comm ] using h_eq w v hwv ( by tauto );
          · simp_all +decide [ le_antisymm hwv hvw ];
      · intro b hb;
        refine' ⟨ _, _, _ ⟩;
        refine' SimpleGraph.mk fun x y => x ≠ y ∧ ( x < y ∧ ( x, y ) ∈ b ∨ y < x ∧ ( y, x ) ∈ b ∨ x ∈ S ∧ y ∈ S ∧ x ≠ y );
        · simp_all +decide [ SimpleGraph.isNClique_iff ];
          intro x hx y hy hxy; aesop;
        · grind;
    -- The number of edges in the graph is $\binom{n}{2}$, and the number of edges in the clique $S$ is $\binom{k}{2}$.
    have h_edges : Finset.card (Finset.filter (fun e => e.1 < e.2) (Finset.univ : Finset (Fin n × Fin n))) = Nat.choose n 2 ∧ Finset.card (Finset.filter (fun e => e.1 < e.2 ∧ e.1 ∈ S ∧ e.2 ∈ S) (Finset.univ : Finset (Fin n × Fin n))) = Nat.choose k 2 := by
      constructor;
      · rw [ Nat.choose_two_right ];
        convert Finset.card_filter ( fun e : Fin n × Fin n => e.1 < e.2 ) ( Finset.univ : Finset ( Fin n × Fin n ) ) using 1;
        erw [ Finset.sum_product ];
        rw [ ← Finset.sum_range_id ];
        simp +decide [ Finset.sum_ite, Finset.filter_lt_eq_Ioi ];
        rw [ ← Finset.sum_range_reflect, Finset.sum_range ];
      · have h_edges_in_S : Finset.card (Finset.filter (fun e => e.1 < e.2 ∧ e.1 ∈ S ∧ e.2 ∈ S) (Finset.univ : Finset (Fin n × Fin n))) = Finset.card (Finset.powersetCard 2 S) := by
          refine' Finset.card_bij _ _ _ _;
          use fun a ha => { a.1, a.2 };
          · grind;
          · simp +contextual [ Finset.Subset.antisymm_iff, Finset.subset_iff ];
            grind;
          · simp +decide [ Finset.mem_powersetCard ];
            intro b hb hb'; rw [ Finset.card_eq_two ] at hb'; obtain ⟨ a, b, hab, rfl ⟩ := hb'; cases lt_trichotomy a b <;> aesop;
        aesop;
    -- The set of edges not in the clique $S$ is the difference between the set of all edges and the set of edges in the clique $S$.
    have h_edges_diff : Finset.filter (fun e => e.1 < e.2 ∧ (e.1 ∉ S ∨ e.2 ∉ S)) (Finset.univ : Finset (Fin n × Fin n)) = Finset.filter (fun e => e.1 < e.2) (Finset.univ : Finset (Fin n × Fin n)) \ Finset.filter (fun e => e.1 < e.2 ∧ e.1 ∈ S ∧ e.2 ∈ S) (Finset.univ : Finset (Fin n × Fin n)) := by
      grind;
    simp_all +decide [ Finset.card_sdiff ];
    rw [ ← h_edges.2, Finset.inter_comm ];
    exact congr_arg _ ( congr_arg _ ( by ext; aesop ) );
  -- Similarly, for a fixed $S$, the number of graphs where $S$ is an independent set is $2^{\binom{n}{2} - \binom{k}{2}}$.
  have h_count_indep_sets (S : Finset (Fin n)) (hS : S.card = k) : (Finset.card (Finset.filter (fun G => Gᶜ.IsNClique k S) (Finset.univ : Finset (SimpleGraph (Fin n))))) = 2 ^ (Nat.choose n 2 - Nat.choose k 2) := by
    convert h_count_cliques S hS using 1;
    fapply Finset.card_bij (fun G _ => Gᶜ);
    · simp +contextual [ SimpleGraph.isNClique_iff ];
    · aesop;
    · exact fun G hG => ⟨ Gᶜ, by aesop ⟩;
  -- By combining the results for cliques and independent sets, we get the total number of monochromatic $k$-cliques.
  have h_total_bad_cliques : (∑ G : SimpleGraph (Fin n), (count_bad_cliques G k : ℝ)) = ∑ S ∈ Finset.powersetCard k (Finset.univ : Finset (Fin n)), (∑ G : SimpleGraph (Fin n), (if G.IsNClique k S then 1 else 0) + ∑ G : SimpleGraph (Fin n), (if Gᶜ.IsNClique k S then 1 else 0)) := by
    simp +decide [ count_bad_cliques ];
    simp +decide only [Finset.card_filter];
    simp +decide only [Nat.cast_sum, Finset.sum_add_distrib];
    exact congrArg₂ ( · + · ) ( Finset.sum_comm ) ( Finset.sum_comm );
  simp_all +decide [ mul_assoc ];
  rw [ Finset.sum_congr rfl fun x hx => by rw [ h_count_cliques x ( Finset.mem_powersetCard.mp hx |>.2 ), h_count_indep_sets x ( Finset.mem_powersetCard.mp hx |>.2 ) ] ] ; norm_num ; ring

#check Nat.choose_le_choose

#check pow_sub₀

/-
If the expected number of monochromatic cliques is less than 1, there exists a graph with no monochromatic cliques.
-/
lemma probabilistic_bound (n k : ℕ)
    (h : (Nat.choose n k : ℝ) * 2 * (1 / 2) ^ (Nat.choose k 2) < 1) :
    ∃ (G : SimpleGraph (Fin n)),
      (∀ s : Finset (Fin n), s.card = k → ¬G.IsNClique k s) ∧
      (∀ s : Finset (Fin n), s.card = k → ¬Gᶜ.IsNClique k s) := by
        -- Let's choose a graph $G$ on $n$ vertices such that the expected number of monochromatic $k$-cliques in $G$ is less than 1.
        obtain ⟨G, hG⟩ : ∃ G : SimpleGraph (Fin n), (count_bad_cliques G k : ℝ) < 1 := by
          -- By the properties of the sum of non-negative terms, if the total sum is less than 1, then at least one of the terms must be less than 1.
          have h_exists_lt_one : ∃ G : SimpleGraph (Fin n), (count_bad_cliques G k : ℝ) < 1 := by
            have h_sum : ∑ G : SimpleGraph (Fin n), (count_bad_cliques G k : ℝ) < 2 ^ (Nat.choose n 2) := by
              convert mul_lt_mul_of_pos_right h ( pow_pos ( zero_lt_two' ℝ ) ( Nat.choose n 2 ) ) using 1;
              · rw [ sum_count_bad_cliques_eq ] ; ring;
                by_cases h₂ : k.choose 2 ≤ n.choose 2 <;> simp_all +decide [ mul_assoc, mul_comm, mul_left_comm, pow_add ];
                · exact Or.inl ( eq_div_of_mul_eq ( by positivity ) ( by rw [ ← pow_add, Nat.sub_add_cancel h₂ ] ) );
                · exact Or.inr <| Nat.choose_eq_zero_of_lt <| by contrapose! h₂; exact Nat.choose_le_choose _ <| by linarith;
              · ring
            contrapose! h_sum;
            convert Finset.sum_le_sum fun G _ => h_sum G;
            -- The sum of 1 over all graphs is just the cardinality of the set of all graphs, which is $2^{\binom{n}{2}}$.
            have h_card : Finset.card (Finset.univ : Finset (SimpleGraph (Fin n))) = 2 ^ (Nat.choose n 2) := by
              have h_card : Finset.card (Finset.univ : Finset (SimpleGraph (Fin n))) = Finset.card (Finset.powerset (Finset.filter (fun e => e.1 < e.2) (Finset.univ : Finset (Fin n × Fin n)))) := by
                have h_card : Finset.card (Finset.univ : Finset (SimpleGraph (Fin n))) = Finset.card (Finset.image (fun E : Finset (Fin n × Fin n) => SimpleGraph.mk (fun i j => i ≠ j ∧ (i, j) ∈ E ∨ j ≠ i ∧ (j, i) ∈ E)) (Finset.powerset (Finset.filter (fun e => e.1 < e.2) (Finset.univ : Finset (Fin n × Fin n))))) := by
                  congr with G;
                  simp +zetaDelta at *;
                  refine' ⟨ Finset.filter ( fun e => G.Adj e.1 e.2 ) ( Finset.filter ( fun e => e.1 < e.2 ) ( Finset.univ : Finset ( Fin n × Fin n ) ) ), _, _ ⟩ <;> simp +decide [ SimpleGraph.adj_comm ];
                  ext i j; by_cases hij : i = j <;> simp +decide [ hij, SimpleGraph.adj_comm ] ;
                  grind;
                rw [ h_card, Finset.card_image_of_injOn ];
                intro E hE E' hE' h_eq; simp_all +decide [ Finset.ext_iff, Set.ext_iff ] ;
                intro i j; have := congr_fun ( congr_fun h_eq i ) j; have := congr_fun ( congr_fun h_eq j ) i; simp_all +decide [ Set.subset_def ] ;
                grind;
              rw [ h_card, Finset.card_powerset ];
              rw [ show Finset.filter ( fun e : Fin n × Fin n => e.1 < e.2 ) Finset.univ = Finset.biUnion ( Finset.univ : Finset ( Fin n ) ) fun i => Finset.image ( fun j => ( i, j ) ) ( Finset.Ioi i ) from ?_, Finset.card_biUnion ];
              · simp +decide [ Finset.card_image_of_injective, Function.Injective ];
                exact Eq.symm ( Nat.recOn n ( by norm_num ) fun n ih => by cases n <;> simp +decide [ Nat.choose, Fin.sum_univ_succ ] at * ; linarith );
              · exact fun i _ j _ hij => Finset.disjoint_left.mpr fun x hx₁ hx₂ => hij <| by aesop;
              · ext ⟨ i, j ⟩ ; aesop;
            aesop;
          exact h_exists_lt_one;
        use G;
        norm_cast at hG; simp_all +decide [ count_bad_cliques ] ;

/-
For $k \ge 3$, $\frac{2^{1+k/2}}{k!} < 1$.
-/
lemma arithmetic_bound_aux (k : ℕ) (hk : 3 ≤ k) :
    (2 : ℝ) ^ (1 + k / 2 : ℝ) / Nat.factorial k < 1 := by
  rw [ div_lt_one ] <;> norm_num ; induction' hk with k hk ih <;> norm_num [ Nat.factorial_succ ] at *;
  · rw [ show ( 5 / 2 : ℝ ) = 2 + 1 / 2 by norm_num, Real.rpow_add ] <;> norm_num;
    rw [ ← Real.sqrt_eq_rpow ] ; nlinarith [ Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ];
  · refine' lt_of_le_of_lt _ ( mul_lt_mul_of_pos_left ih ( by positivity ) );
    rw [ show ( 1 + ( ( k : ℝ ) + 1 ) / 2 ) = ( 1 + ( k : ℝ ) / 2 ) + 1 / 2 by ring, Real.rpow_add ] <;> norm_num ; ring_nf ; norm_num;
    rw [ ← Real.sqrt_eq_rpow ] ; nlinarith [ sq_nonneg ( Real.sqrt 2 - 2 : ℝ ), Real.sq_sqrt zero_le_two, Real.rpow_pos_of_pos zero_lt_two ( 1 + ( k : ℝ ) * ( 1 / 2 ) ), show ( k : ℝ ) ≥ 3 by norm_cast ];
  · positivity

/-
If `IsRamsey k n` holds and `n \le m`, then `IsRamsey k m` holds.
-/
lemma IsRamsey.mono {k n m : ℕ} (hnm : n ≤ m) (h : IsRamsey k n) : IsRamsey k m := by
  intro G;
  obtain h | h := h ( G.comap ( Fin.castLE hnm ) ) <;> [ left; right ] <;> obtain ⟨ s, hs ⟩ := h <;> use s.image ( Fin.castLE hnm ) <;> simp_all +decide [ SimpleGraph.isNClique_iff ];
  · simp_all +decide [ Set.Pairwise ];
    rw [ Finset.card_image_of_injective _ fun x y hxy => by simpa [ Fin.ext_iff ] using hxy, hs.2 ];
  · simp_all +decide [ SimpleGraph.IsIndepSet, Finset.card_image_of_injective, Function.Injective ];
    intro v hv w hw hvw; aesop;

#check Nat.lt_floor_add_one
#check Nat.choose_le_pow
#check Nat.descFactorial_le_pow

#check Real.rpow_neg
#check Real.rpow_neg_one
#check Nat.lt_floor_add_one

#check Real.inv_rpow
#check Nat.lt_floor_add_one
#check Nat.sInf_mem

/-
The probabilistic condition holds for $n = \lfloor 2^{k/2} \rfloor$.
-/
lemma probabilistic_condition (k : ℕ) (hk : 3 ≤ k) :
    let n := Nat.floor ((Real.sqrt 2) ^ k)
    (Nat.choose n k : ℝ) * 2 * (1 / 2) ^ (Nat.choose k 2) < 1 := by
      -- We show that $(n \text{ choose } k) \le n^k / k!$.
      have h_choose : (Nat.choose ⌊(Real.sqrt 2) ^ k⌋₊ k : ℝ) ≤ (⌊(Real.sqrt 2) ^ k⌋₊ : ℝ) ^ k / Nat.factorial k := by
        rw [ le_div_iff₀ <| by positivity ];
        rw_mod_cast [ Nat.mul_comm ];
        rw [ ← Nat.descFactorial_eq_factorial_mul_choose ];
        exact Nat.descFactorial_le_pow _ _;
      -- Substitute the bound from `h_choose` into our inequality.
      suffices h_bound : (⌊(Real.sqrt 2) ^ k⌋₊ : ℝ) ^ k / Nat.factorial k * 2 * (1 / 2) ^ (Nat.choose k 2) < 1 by
        exact lt_of_le_of_lt ( mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_right h_choose zero_le_two ) ( by positivity ) ) h_bound;
      -- We use $n \leq 2^{k/2}$ to bound the expression.
      have h_bound : (⌊(Real.sqrt 2) ^ k⌋₊ : ℝ) ^ k / Nat.factorial k * 2 * (1 / 2) ^ (Nat.choose k 2) ≤ (2 ^ (k / 2 : ℝ) : ℝ) ^ k / Nat.factorial k * 2 * (1 / 2) ^ (Nat.choose k 2) := by
        gcongr;
        exact le_trans ( Nat.floor_le <| by positivity ) <| by rw [ show ( 2 : ℝ ) ^ ( ( k : ℝ ) / 2 ) = ( Real.sqrt 2 ^ k ) by rw [ Real.sqrt_eq_rpow, ← Real.rpow_natCast, ← Real.rpow_mul ] <;> ring_nf ; norm_num ] ;
      refine lt_of_le_of_lt h_bound ?_;
      -- Simplify the expression to get $\frac{2^{k^2/2 + 1 - (k^2-k)/2}}{k!} = \frac{2^{(k+2)/2}}{k!}$.
      suffices h_simplify : (2 ^ ((k ^ 2 : ℝ) / 2 + 1 - (Nat.choose k 2 : ℝ)) : ℝ) / Nat.factorial k < 1 by
        convert h_simplify using 1 ; norm_num [ Real.rpow_sub ] ; ring;
        rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ) ] ; ring;
        rw [ Real.rpow_add ] <;> norm_num ; ring;
      rw [ show ( k.choose 2 : ℝ ) = k * ( k - 1 ) / 2 by exact Nat.recOn k ( by norm_num ) fun n ih => by norm_num [ Nat.choose ] at * ; linarith ] ; ring_nf ; norm_num;
      convert arithmetic_bound_aux k hk using 1 ; ring

/-
$R(k) > (\sqrt{2})^k$ for $k \ge 3$.
-/
theorem diagonalRamsey_gt_sqrt2_pow_k (k : ℕ) (hk : 3 ≤ k) (h_ramsey : ∃ M, IsRamsey k M) :
    (diagonalRamsey k : ℝ) > (Real.sqrt 2) ^ k := by
      -- Let $n = \lfloor 2^{k/2} \rfloor$. We show that `IsRamsey k n` is false.
      have probabilistic_bound : ¬IsRamsey k (Nat.floor ((Real.sqrt 2) ^ k)) := by
        unfold IsRamsey;
        push_neg;
        have := probabilistic_bound ⌊ ( Real.sqrt 2 ) ^ k⌋₊ k ( by simpa using probabilistic_condition k hk );
        obtain ⟨ G, hG₁, hG₂ ⟩ := this;
        refine' ⟨ G, fun s hs => _, fun s hs => _ ⟩;
        · exact hG₁ s hs.card_eq hs;
        · exact hG₂ s ( by simpa [ SimpleGraph.isNClique_iff ] using hs.2 ) hs;
      -- By definition of $R(k)$, if $R(k) \leq \lfloor 2^{k/2} \rfloor$, then `IsRamsey k (⌊2^{k/2}⌋)` would be true.
      have h_inf : diagonalRamsey k > Nat.floor ((Real.sqrt 2) ^ k) := by
        exact lt_of_not_ge fun h => probabilistic_bound <| Nat.sInf_mem h_ramsey |> fun h' => IsRamsey.mono h h';
      exact Nat.lt_of_floor_lt h_inf